[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
base = "dark"
baseFontSize = 16

primaryColor = "#73C990"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#333333"
textColor = "#D4D4D4"
linkColor = "#3B8FE9"
codeBackgroundColor = "#252526"
font = "SpaceGrotesk"
codeFont = "SpaceMono"
baseRadius = ".2rem"