[theme]
base="dark"
backgroundColor="#162025"
secondaryBackgroundColor="indigo"
codeBackgroundColor="darkSlateGrey"

[theme.sidebar]
backgroundColor="#253137"
secondaryBackgroundColor="darkGoldenrod"
