[theme]
base="light"
backgroundColor="aliceBlue"
secondaryBackgroundColor="thistle"
codeBackgroundColor="powderBlue"

[theme.sidebar]
backgroundColor="lightSteelBlue"
secondaryBackgroundColor="antiqueWhite"
