backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/index.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
  - name: "contents"
    label: "Documentation"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Icon", name: "icon", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}