backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: /img
collections:
- name: "pages"
  label: "Pages"
  files:
  - label: "Home"
    name: "home"
    file: "content/index.md"
    fields:
    - label: Title
      name: title
      widget: string
    - label: Body
      name: body
      widget: markdown
- name: "contents"
  label: "Documentation"
  folder: "content"
  create: true
  slug: "{{slug}}"
  fields:
  - label: Title
    name: title
    widget: string
  - label: Next Page
    name: next
    widget: relation
    collection: "contents"
    valueField: slug
    searchFields: ["title","category"]
    hint: "Categories should be seperated by back slashes (Parent / Child / Child)"
  - label: Page Catgeory
    name: category
    widget: string
  - label: Body
    name: body
    widget: markdown