backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: /img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/index.md"
      fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: "contents"
    label: "Documentation"
    label_singular: 'Document'
    folder: "content"
    create: true
    slug: "{{slug}}"
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    fields:
    - label: Title
      name: title
      widget: string
    - label: Body
      name: body
      widget: markdown