name: build-search-index
run-name: Regenerate Algolia's search index
on: [push]
# on:
#   push:
#     branches:
#       - 'main'
jobs:
  build-search-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build
      - run: node ./scripts/build-search-index.js
